### ISSUE TITLE
accelerator/clutch/brake pedals

### ISSUE THREAD

**Issue by shubin** [knaufinator/6DOF-Rotary-Stewart-Motion-Simulator#12]
Hi Christopher,
I've been watching your videos and I noticed that you use regular automotive e-gas pedals for all the foot pedals.
I found a cheap e-gas pedal for a test and that pedal seems to have much lesser angle range than those you use.
Could you please share the part number of the pedals you use?

**Comment by knaufinator** [comment]
shubin, I am using the Fanatec pedal set CSL Elite Pedals LC. I then only mounted them inverted and carefully positioned them to work with me in the position I sit in. The E-Brake is an actual modified brake handle with a switch fabricated in. 

https://www.amazon.com/Sporacingrts-Hydraulic-Handbrake-Universal-Adjustable/dp/B07TC52GTD/ref=sr_1_6?dchild=1&keywords=ebrake&qid=1606653965&sr=8-6
